#!/usr/bin/python

import re
import time
import json
import urllib3
import requests
import pytz
import traceback
import time
import sys
from os.path import isfile, join
from os import remove, walk, environ
from datetime import datetime, timedelta, date
from urlparse import urlparse

from hosted import config


def cache_image(url):
    image_url = urlparse(url)
    image_filename = image_url.path.split("/")[-1]
    if not isfile(image_filename):
        try:
            with open(image_filename, "wb") as f:
                r = session.get(url)
                r.raise_for_status()
                f.write(r.content)
        except Exception as e:
            sys.stderr.write(
                "[gts] exception while caching image {} - {}\n".format(url, e)
            )
            return None
    return image_filename


class GTSPost:
    def __init__(self, post, domain):
        self.post = post
        self.profile_image = None
        self.attachment_image = None
        self.domain = domain

    def _log(self, text):
        sys.stderr.write("[GTS] [toot {}] {}\n".format(self, text))

    def __str__(self):
        return self.post["id"]

    def cache_images(self):
        self.profile_image = cache_image(self.post["account"]["avatar_static"])
        for attachment in self.post.get("media_attachments", set()):
            if attachment["type"] == "image":
                if (
                    attachment["meta"]["original"]["width"] > 2048
                    or attachment["meta"]["original"]["height"] > 2048
                ):
                    self.attachment_image = cache_image(attachment["preview_url"])
                else:
                    self.attachment_image = cache_image(attachment["url"])
                break

    @property
    def text(self):
        string = self.post["text"]
        # I know, this could be done using HTMLParser - but this opens a can
        # of worms because we're dealing with python2.7 and unicode.
        for source, replacement in {
            "&nbsp;": " ",
            "&#160;": " ",
            "&amp;": "&",
            "&#38;": "&",
            "&gt;": ">",
            "&#62;": ">",
            "&lt;": "<",
            "&#60;": "<",
            "&quot;": '"',
            "&#34;": '"',
            "&apos;": "'",
            "&#39;": "'",
            "<br>": " ",
            "<br />": " ",
            "</p><p>": " ",
        }.items():
            string = string.replace(source, replacement)
        string = re.sub("<[^>]+>", "", string)
        return string

    @property
    def account_name(self):
        return "{}@{}".format(
            self.post["account"]["acct"],
            self.domain,
        )

    @property
    def created_timestamp(self):
        date_time_obj = datetime.strptime(
            self.post["created_at"][0:-1], "%Y-%m-%dT%H:%M:%S.%f"
        )
        return int(time.mktime(date_time_obj.timetuple()))


class GTSFetcher:
    def __init__(self):
        self.session = requests.Session()
        self.session.headers = {
            "User-Agent": "info-beamer poller serial {}".format(
                environ.get("SERIAL", "unknown")
            ),
            "Accept": "application/json",
        }
        self.not_before = int(
            time.mktime(datetime.strptime(config.not_before, "%Y-%m-%d").timetuple())
        )
        self.posts = []

    def _log(self, something):
        if not isinstance(something, str):
            something = repr(something)
        sys.stderr.write("[gts] {}\n".format(something))

    def _fetch(self, url):
        self._log("starting _fetch('{url}')".format(url))
        r = session.get(url)
        self._log("http status code was {}".format(r.status_code))
        r.raise_for_status()
        return r.json()

    def fetch_and_parse(self):
        try:
            instance = self._fetch("{}/api/v1/instance".format(config.baseurl))

            toots = self._fetch(
                "{baseurl}/api/v1/timelines/public?local=true&limit={limit}".format(
                    baseurl=config.baseurl,
                    limit=config.count,
                )
            )
            for post in toots:
                toot = GTSPost(post, instance["account_domain"])
                if toot in self.posts:
                    self._log("ignoring {} because duplicate".format(toot))
                    continue
                if toot.created_timestamp < self.not_before:
                    self._log(
                        "ignoring {} because it was created too long ago (is {}, want {})".format(
                            toot, toot.created_timestamp, self.not_before
                        ),
                    )
                    continue
                self.posts.append(toot)
        except Exception as e:
            self._log(e)

    def cache_and_cleanup_images(self):
        images = {"gts-logo.png", "node.png", "package.png", "package-header.jpg"}
        to_delete = set()
        for post in self.posts:
            post.cache_images()
            for path in (post.profile_image, post.attachment_image):
                if path is not None:
                    images.add(path)
        for root, dirs, files in walk("./"):
            for name in files:
                if (
                    name.endswith("png")
                    or name.endswith("jpg")
                    or name.endswith("jpeg")
                    or name.endswith("gif")
                ) and name not in images:
                    to_delete.add(name)
        for path in to_delete:
            self._log("deleting image {} because it's not used anywhere".format(path))
            remove(path)

    def dump_json(self):
        out = []
        for post in self.posts:
            out.append(
                {
                    "created_at": post.created_timestamp,
                    "content": post.text,
                    "account": {
                        "acct": post.account_name,
                        "display_name": post.post["account"]["display_name"],
                        "avatar_static": post.profile_image,
                    },
                    "media_attachment": post.attachment_image or "",
                }
            )
        self._log("have gotten {} posts in total".format(len(out)))
        if len(out) > 0:
            with open("tootlist.json", "wb") as f:
                f.write(json.dumps(out, ensure_ascii=False).encode("utf8"))
            self._log("wrote {} posts to tootlist.json".format(len(out)))


def main():
    config.restart_on_update()

    if config.poll_interval == 0:
        print >> sys.stderr, "waiting for a config change"
        while 1:
            time.sleep(100000)

    while 1:
        try:
            poller = GTSFetcher()
            poller.fetch_and_parse()
            poller.cache_and_cleanup_images()
            poller.dump_json()
        except:
            traceback.print_exc()
            time.sleep(60)
        else:
            time.sleep(60 * config.poll_interval)


if __name__ == "__main__":
    main()
